name: d-form

# nk ngerubah docker-compose.prod.yml ati ati ya kang
# soal e iki nggo pipeline ng CI/CD 
# nk meh ngerubah kondo fa'iz sek ya
services:
  db:
    image: mariadb:10.11
    container_name: d-form-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_DATABASE:?DB_DATABASE is required}
      MARIADB_USER: ${DB_USERNAME:?DB_USERNAME is required}
      MARIADB_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is required}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?DB_ROOT_PASSWORD is required}
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - d-form-internal

    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:8.0-alpine
    container_name: d-form-redis
    restart: unless-stopped
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--stop-writes-on-bgsave-error",
        "no"
      ]
    volumes:
      - redis_data:/data
    networks:
      - d-form-internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.prod

    container_name: d-form-app-core
    restart: unless-stopped
    expose:
      - "8000"
    env_file:
      - ${APP_ENV_FILE:-.env.production}
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      doscom_ingress:
        aliases:
          - d-form-app
      d-form-internal: {}
    volumes:
      - app_storage:/app/storage/app
    stop_grace_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  doscom_ingress:
    external: true
    name: doscom_ingress

  d-form-internal:
    driver: bridge
    internal: true

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  app_storage:
    driver: local

secrets:
  db_root_password:
    environment: DB_ROOT_PASSWORD