FROM dunglas/frankenphp:php8.3-alpine

ARG UID=1000
ARG GID=1000

RUN install-php-extensions \
    pcntl \
    zip \
    bcmath \
    intl \
    imagick \
    pdo_mysql \
    redis

COPY . /app

# RUN groupadd -g $GID appuser && useradd -u $UID -g appuser -ms /bin/bash appuser
RUN addgroup -g $GID -S appuser && adduser -u $UID -G appuser -s /bin/sh -D -S appuser

RUN chown -R appuser:appuser /app

ENTRYPOINT ["php", "artisan", "octane:frankenphp"]

USER appuser

CMD ["--watch", "--workers=1", "--max-requests=1"]
